Repository 2024-line4-earth/New_Joinus_BE, pull requests merged in 2025-05, with the labels that each got.

#24 Hotfix/21 prod config
  .gitignore
  newjoinus/settings/base.py
  newjoinus/settings/prod.py
  requirements.txt
Labels: bug

#35 Hotfix/33 points
  join/services/points.py
Labels: bug

#45 hotfix/37 tutorial
  constants/service_config_constants.py
  join/serializers/tutorial_state.py
  join/services/__init__.py
  join/services/tutorial_state.py
  join/views/card_post.py
Labels: bug

#48 Feature/43 image
  constants/service_config_constants.py
  join/serializers/card_post.py
  join/services/s3.py
  join/utils.py
Labels: enhancement

#50 Hotfix/46 points
  constants/service_config_constants.py
  join/migrations/0004_add_was_shared_to_cardpost_and_backfill.py
  join/models/card_post.py
  join/serializers/card_post.py
  share/migrations/0003_alter_sharedcard_cardpost.py
  share/migrations/0004_remove_invalid_sharedcards.py
  share/models/shared_card.py
  share/serializers/shared_card.py
  share/urls.py
  share/views/shared_card.py
Labels: bug, enhancement

#55 feature/54 storedcard
  share/migrations/0008_storedcard.py
  share/models/__init__.py
  share/models/stored_card.py
  share/serializers/stored_card.py
  share/services/stored_card.py
  share/urls.py
  share/views/stored_card.py
Labels: enhancement

#56 Feature/53 card get
  join/urls.py
  join/views/__init__.py
  join/views/card_post.py
  share/migrations/0009_rename_pinnedsharedcard_pinnedcard.py
  share/models/__init__.py
  share/models/pin.py
  share/pagination.py
  share/serializers/pin.py
  share/serializers/shared_card.py
  share/services/pin.py
  share/urls.py
  share/views/pin.py
  share/views/shared_card.py
Labels: enhancement

#61 feature/58 points
  constants/service_config_constants.py
  join/migrations/0005_cardpost_has_image_url_share_been_notified.py
  join/models/card_post.py
  join/serializers/card_post.py
  join/urls.py
  join/views/__init__.py
  join/views/card_post.py
Labels: enhancement

#62 Feature/59 mission
  constants/service_config_constants.py
  join/admin.py
  share/admin.py
  share/migrations/0010_usermissionstate_cardmission.py
  share/migrations/0011_add_usermissionstate.py
  share/models/__init__.py
  share/models/mission.py
  share/scripts/reset_missions.py
  share/serializers/shared_card.py
  share/urls.py
  share/views/mission.py
  users/apps.py
  users/signals.py
Labels: enhancement

#70 feat: 아이템 이미지 다운로드 기능 구현 및 포인트 로직 수정
  join/services/points.py
  market/migrations/0002_item_image_key.py
  market/models.py
  market/serializers.py
  market/urls.py
  market/views.py
Labels: bug, enhancement

#72 feat: 랭킹앱 내 순위 포함한 공유 글 리스트 구현
  ranking/urls.py
  ranking/views.py
Labels: enhancement

#74 fix: 원본 이미지 직접 업로드
  join/services/s3.py
  market/views.py
Labels: bug
